.TH PADINF 1
.SH NAME
\fBpadinf\fR \-\- prints padding information
.SH SYNOPSIS
\fBpadinf\fR [\fIOPTION\fR...] [input=\fIFILE\fR]
.SH DESCRIPTION
\fBpadinf\fR prints padding information.
.SH OPTIONS
.TP
.B \-a, \-\-align=\fINUM\fR
Alignment [default=\fB16384\fR]
.SH EXAMPLE
\fBpadinf -a 16384 a.bin\fR
